// packages/carts-react/src/Carts.tsx
import React, { useState } from 'react'

import Cart from './Cart'

import { useStore } from 'koala-store'
import { STORES, CartState, Cart as ICart } from 'types'

const Carts = (): JSX.Element => {
  const { dispatch, store } = useStore<CartState>(STORES.CARTS)
  const [ carts, setCarts ] = useState<ICart[]>(store.getState().carts)

  const removeCart = (cart: ICart) => {
    dispatch({ type: 'removeCart', payload: cart })
  }

  store.subscribe(() => {
    const state = store.getState()
    setCarts(state.carts)
  })

  return (
    <main style={{
      width: '50rem',
      maxWidth: '90%',
      margin: '2rem auto'      
    }}>
    { 
      (carts && carts.length) 
        ? (
            <ul style={{
              listStyle: 'none',
              margin: 0,
              padding: 0
            }}>
              { 
                carts.map((cart, index) => {
                  return <Cart key={index} cart={cart} removeCart={() => removeCart(cart)} />
                }) 
              }
            </ul>
          )
        : (
            <p style={{ textAlign: 'center' }}> 
              No Item in the Cart!
            </p>
          )
      }
      </main>
  )
}

export default Carts

// packages/carts/src/Carts.vue
<template>
  <main class="carts">
    <p v-if="carts && carts.length <= 0">
      No Item in the Cart!
    </p>
    <ul>
      <li v-for="(product, index) in carts" :key="index">
        <Cart :product="product" @remove="removeCart(product)" />
      </li>
    </ul>
  </main>
</template>

<script lang="ts">
import { CartState, Cart as ICart, STORES } from 'types'
import { useStore } from 'koala-store'

import Cart from './Cart.vue'

export default {
  name: 'Carts',
  components: {
    Cart
  },
  setup() {
    const { getter, dispatch } = useStore<CartState>(STORES.CARTS)

    const carts = getter((state) => state.carts)

    const removeCart = (product: ICart) => 
      dispatch({ type: 'removeCart', payload: product })

    return { carts, removeCart }
  }
}
</script>

<style lang="scss">
.carts {
  width: 50rem;
  max-width: 90%;
  margin: 2rem auto;

  p {
    text-align: center;
  }

  ul {
    list-style: none;
    margin: 0;
    padding: 0;
  }
}
</style>
