// packages/carts/src/Cart.vue
<template>
  <div class="cart">
    <div>
      <strong>{{ product.title }}</strong> - {{ product.price }} ({{ product.quantity }})
    </div>
    <div>
      <button @click="removeFromCart()">Remove from Cart</button>
    </div>
  </div>
</template>

<script>
import { toRefs } from 'vue'

export default {
  name: 'Cart',
  props: [ 'product' ],
  setup(props, { emit }) {
    const removeFromCart = () => emit('remove', props.product) 

    return { ...toRefs(props), removeFromCart }
  }
}
</script>

<style lang="scss">
.cart {
  padding: 1rem;
  margin: 1rem 0;
  border: 1px solid #00179b;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
</style>

// packages/carts-react/src/Cart.tsx
import React from 'react'
import { Cart as ICart } from 'types'

export interface CartProps {
  cart?: ICart
  removeCart?: () => void
}

const Cart = (props: CartProps): JSX.Element => {
  return (
    <li>
      <div style={{
        padding: '1rem',
        margin: '1rem 0',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        border: '1px solid #35495e'
      }}>
        <div>
          <strong>{props.cart.title}</strong> - { props.cart.price } ({props.cart.quantity})
        </div>
        <div>
          <button onClick={props.removeCart}>Remove from Cart</button>
        </div>
      </div>
    </li>
  )
}

export default Cart
